### ISSUE TITLE
와우

### ISSUE THREAD

**Issue by genius0412** [SaidBySolo/auto-self-diagnosis#1]
!!!!

다운로드 받아서 실행했더니

WINDOWS 방화벽 ~~ 차단 ~~ 뜨는데 허용 해야 하나요?

**Comment by SaidBySolo** [comment]
네

크롬 웹드라이버와 웹소켓통신으로 제어하므로 방화벽 풀어주셔야합니다.

**Comment by SaidBySolo** [comment]
24시간이내에 질문 혹은 더이상 도와드릴것이없으면 이슈 Close하겠습니다.

**Comment by SaidBySolo** [comment]
더이상 문제가 없는듯하니 close하겠습니다 다른도와드릴것이있다면 이슈를 다시 open해주세요

**Comment by genius0412** [comment]
네 감사합니당

**Comment by ghost** [comment]
당근이쥬!
