### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by NoaHimesaka1873** [SaidBySolo/auto-self-diagnosis#18]
리눅스로 cron 돌리려고 하는데 리눅스 서포트는 없나요? 아치리눅스 롤링릴리즈 사용중

**Comment by NoaHimesaka1873** [comment]
EDIT: 소스 다운받아서 웹드라이버파일만 리눅스용으로 지정해주고 Python으로 직접 실행하면 작동합니다
`if getattr(sys, "frozen", False):` 이거 부분을
```
if getattr(sys, "frozen", False):
    driver = webdriver.Chrome("/bin/chromedriver", options=options)
else:
    driver = webdriver.Chrome("/bin/chromedriver", options=options)
```
경로만 자기 웹드라이버 경로로 수정 해주시고 selenium을 pip로 설치해 주시면 잘 작동합니다.
![Screenshot_20200909_100758](https://user-images.githubusercontent.com/39993457/92542672-5bebb400-f284-11ea-8298-973dc110b70f.png)
작동 인증

EDIT: macOS도 이런 방법으로 사용 가능합니다

**Comment by SaidBySolo** [comment]
# 리눅스는 빌드하지 않을 예정입니다.

하지만 직접 소스 수정하셔서 쓰시면됩니다.

## 요구사항

4.0.0 기준으로 요구사항은 이렇습니다.

Google Chrome 85
ChromeDriver 85
python 3.6+ (development in 3.8)
selenium

## 그래서 제가 뭘하면 되나요?

Chrome과 ChromeDriver를 전부 받아주시고

해당 레포를 클론합니다.
```
git clone https://github.com/SaidBySolo/auto-self-diagnosis.git
```

해당 디렉토리로 이동하신다음
```
cd auto-self-diagnosis
```
의존성을 설치합니다.
```
pip install -r requirements.txt
```

이 이후로는 크롬드라이버를 같은 소스내에 위치시키고
크롬드라이버 불러오는곳과 json을 직접 수정하신다음 쓰시면 됩니다.

**Comment by SaidBySolo** [comment]
해당 이슈가 또올라올거같기때문에 핀해놓겠습니다.

**Comment by NoaHimesaka1873** [comment]
아예 README에 적어놓으시는게 어떠신가요?

**Comment by SaidBySolo** [comment]
리드미... 까지는 써놓을 필요는 없을거같네요
왜냐하면 일반 사용자가 리눅스를 쓰는일은 흔치않을꺼라 예상되네요 :)

**Comment by NoaHimesaka1873** [comment]
그렇죠. macOS도 같은 방법이 적용되지만 쓸 사람이 (거의) 없겠죠. :( 맥유져는 웁니다
