### ISSUE TITLE
3분 이내 반복설문 예외 처리, release 5.0.0 라이브러리 미포함

### ISSUE THREAD

**Issue by juny1209** [SaidBySolo/auto-self-diagnosis#21]
![image](https://user-images.githubusercontent.com/28196117/94639483-39930680-0317-11eb-9917-682e2bcdd479.png)
![image](https://user-images.githubusercontent.com/28196117/94639379-02245a00-0317-11eb-9a8e-b256100a671f.png)
자가진단을 3분 이내에 1번 이상 반복하면 다음과 같이 예외가 발생하며 프로그램이 종료되지 않습니다. 예외 처리를 하는 게 좋아보여요. 작업 스케쥴러로 백그라운드에서 아침마다 실행되게 하려고 테스트 할 때 로그가 안보이다 보니 사이트 구성이 변경된 줄 알고 삽질했네요..

이와 더불어서,
![image](https://user-images.githubusercontent.com/28196117/94639621-9393cc00-0317-11eb-83e7-517aede6be7a.png)
release 5.0.0에 selenium 라이브러리가 포함되어 있지 않은 것 같습니다.

**Comment by SaidBySolo** [comment]
남은 시간에 맞춰 sleep후 재시도하도록 수정했습니다.

**Comment by SaidBySolo** [comment]
Release 5.1.0

https://github.com/SaidBySolo/auto-self-diagnosis/releases/tag/5.1.0
