### ISSUE TITLE
윈도우 7에서 작동 하지 않습니다.

### ISSUE THREAD

**Issue by selfdestruct404** [SaidBySolo/auto-self-diagnosis#25]
5.2.0 버전으로 변경후 
![캡처](https://user-images.githubusercontent.com/65072149/98664915-53038580-238e-11eb-9d4b-855dbb8a0981.PNG)가 뜨며 실행이 되지 않습니다 윈도우 7 에서의 사용은 불가능 한건가요?

**Comment by SaidBySolo** [comment]
Windows 10에서는 정상작동을 확인했습니다.

Windows 7을 사용하지 않기 때문에 재현을 할수 없습니다.

혹시 같은 문제가 다른 유저에서도 재현된다면 픽스 해보겠습니다.

이슈는 열어두겠습니다.

혹시 모르니 임시폴더에 ``_MEI`` 라고 있는 폴더를 삭제후 다시 시도해보세요

**Comment by selfdestruct404** [comment]
> Windows 10에서는 정상작동을 확인했습니다.
> 
> Windows 7을 사용하지 않기 때문에 재현을 할수 없습니다.
> 
> 혹시 같은 문제가 다른 유저에서도 재현된다면 픽스 해보겠습니다.
> 
> 이슈는 열어두겠습니다.
> 
> 혹시 모르니 임시폴더에 `_MEI` 라고 있는 폴더를 삭제후 다시 시도해보세요

_MEI는 찾을 수 없었으며 윈도우 7을 사용중인 2개의 PC에서 동일한 현상이 나타났습니다.

**Comment by SaidBySolo** [comment]
해당문제의 원인을 발견했습니다.

https://bugs.python.org/issue40740


Python 3.9는 더이상  Windows 7을 지원하지않습니다.

직접 스크립트를 실행하시거나 python 3.9 이전버전을 다운받으신후에 해당 레포지토리를 클론후 make_exe.bat으로 빌드하신후 사용하세요.
