### ISSUE TITLE
작업스케줄러, 시작프로그램 사용시

### ISSUE THREAD

**Issue by piese1028** [SaidBySolo/auto-self-diagnosis#30]
작업스케줄러나 시작프로그램에 auto-self-diagnosis.py나 auto-self-diagnosis.exe를 넣게되면 아래와 같이 0.몇초 뜨고 꺼져버립니다. 자동자가진단을 자동으로 실행 되게 만들고 싶은데 어떻게 하나요?
![image](https://user-images.githubusercontent.com/61900596/109390246-cfc56a00-7953-11eb-9d78-979b8f4ceee2.png)

**Comment by SaidBySolo** [comment]
info.json을 찾을수없습니다. 경로에 위치시켜주세요.

**Comment by selfdestruct404** [comment]
작업 스케줄러 옵션중에 시작 위치 옵션이 있습니다 시작 위치를 자가진단 실행파일과 info.json 파일이 있는 폴더로 지정 시키시면 가능 합니다

**Comment by piese1028** [comment]
폴더 안에 있습니다
