### ISSUE TITLE
체크 도중 오류

### ISSUE THREAD

**Issue by chaemoong** [SaidBySolo/auto-self-diagnosis#4]
릴리즈가 크롬 83까지만 지원하여 소스 코드를 다운해 크롬드라이버 85버젼을 다운 후 하였으나 아래와 같은 오류 발생후 종료됨
Message: element click intercepted: Element <input type="radio" id="rspns011" name="rspns01" value="1"> is not clickable at point (55, 754). Other element would receive the click: <div class="ui-widget-overlay ui-front" style="z-index: 100;"></div>
  (Session info: headless chrome=85.0.4183.83)

자가진단은 서울시교육청에서 진행한 결과입니다

**Comment by kijk2869** [comment]
서울시 교육청의 지연안내 팝업과 관련됨

**Comment by SaidBySolo** [comment]
fixed
